// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto
package EncodingTutorial.protobuf.schema;

/**
 * Protobuf type {@code Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Person)
    PersonOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Person.newBuilder() to construct.
  private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Person() {
    userName_ = "";
    interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Person();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Person(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            userName_ = bs;
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            favoriteNumber_ = input.readInt64();
            break;
          }
          case 26: {
            com.google.protobuf.ByteString bs = input.readBytes();
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              interests_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            interests_.add(bs);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        interests_ = interests_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return PersonOuterClass.internal_static_Person_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return PersonOuterClass.internal_static_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Person.class, Builder.class);
  }

  private int bitField0_;
  public static final int USER_NAME_FIELD_NUMBER = 1;
  private volatile Object userName_;
  /**
   * <code>required string user_name = 1;</code>
   * @return Whether the userName field is set.
   */
  @Override
  public boolean hasUserName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string user_name = 1;</code>
   * @return The userName.
   */
  @Override
  public String getUserName() {
    Object ref = userName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        userName_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string user_name = 1;</code>
   * @return The bytes for userName.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserNameBytes() {
    Object ref = userName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FAVORITE_NUMBER_FIELD_NUMBER = 2;
  private long favoriteNumber_;
  /**
   * <code>optional int64 favorite_number = 2;</code>
   * @return Whether the favoriteNumber field is set.
   */
  @Override
  public boolean hasFavoriteNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 favorite_number = 2;</code>
   * @return The favoriteNumber.
   */
  @Override
  public long getFavoriteNumber() {
    return favoriteNumber_;
  }

  public static final int INTERESTS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList interests_;
  /**
   * <code>repeated string interests = 3;</code>
   * @return A list containing the interests.
   */
  public com.google.protobuf.ProtocolStringList
      getInterestsList() {
    return interests_;
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @return The count of interests.
   */
  public int getInterestsCount() {
    return interests_.size();
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the element to return.
   * @return The interests at the given index.
   */
  public String getInterests(int index) {
    return interests_.get(index);
  }
  /**
   * <code>repeated string interests = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the interests at the given index.
   */
  public com.google.protobuf.ByteString
      getInterestsBytes(int index) {
    return interests_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasUserName()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, favoriteNumber_);
    }
    for (int i = 0; i < interests_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, interests_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, favoriteNumber_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < interests_.size(); i++) {
        dataSize += computeStringSizeNoTag(interests_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInterestsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Person)) {
      return super.equals(obj);
    }
    Person other = (Person) obj;

    if (hasUserName() != other.hasUserName()) return false;
    if (hasUserName()) {
      if (!getUserName()
          .equals(other.getUserName())) return false;
    }
    if (hasFavoriteNumber() != other.hasFavoriteNumber()) return false;
    if (hasFavoriteNumber()) {
      if (getFavoriteNumber()
          != other.getFavoriteNumber()) return false;
    }
    if (!getInterestsList()
        .equals(other.getInterestsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUserName()) {
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
    }
    if (hasFavoriteNumber()) {
      hash = (37 * hash) + FAVORITE_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFavoriteNumber());
    }
    if (getInterestsCount() > 0) {
      hash = (37 * hash) + INTERESTS_FIELD_NUMBER;
      hash = (53 * hash) + getInterestsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Person parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Person parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Person parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Person parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Person parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Person parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Person)
      PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PersonOuterClass.internal_static_Person_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PersonOuterClass.internal_static_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Builder.class);
    }

    // Construct using Person.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      userName_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      favoriteNumber_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000002);
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return PersonOuterClass.internal_static_Person_descriptor;
    }

    @Override
    public Person getDefaultInstanceForType() {
      return Person.getDefaultInstance();
    }

    @Override
    public Person build() {
      Person result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Person buildPartial() {
      Person result = new Person(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.userName_ = userName_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.favoriteNumber_ = favoriteNumber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        interests_ = interests_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.interests_ = interests_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Person) {
        return mergeFrom((Person)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Person other) {
      if (other == Person.getDefaultInstance()) return this;
      if (other.hasUserName()) {
        bitField0_ |= 0x00000001;
        userName_ = other.userName_;
        onChanged();
      }
      if (other.hasFavoriteNumber()) {
        setFavoriteNumber(other.getFavoriteNumber());
      }
      if (!other.interests_.isEmpty()) {
        if (interests_.isEmpty()) {
          interests_ = other.interests_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureInterestsIsMutable();
          interests_.addAll(other.interests_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      if (!hasUserName()) {
        return false;
      }
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object userName_ = "";
    /**
     * <code>required string user_name = 1;</code>
     * @return Whether the userName field is set.
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string user_name = 1;</code>
     * @return The userName.
     */
    public String getUserName() {
      Object ref = userName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>required string user_name = 1;</code>
     * @return The bytes for userName.
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      Object ref = userName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string user_name = 1;</code>
     * @param value The userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string user_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userName_ = getDefaultInstance().getUserName();
      onChanged();
      return this;
    }
    /**
     * <code>required string user_name = 1;</code>
     * @param value The bytes for userName to set.
     * @return This builder for chaining.
     */
    public Builder setUserNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      userName_ = value;
      onChanged();
      return this;
    }

    private long favoriteNumber_ ;
    /**
     * <code>optional int64 favorite_number = 2;</code>
     * @return Whether the favoriteNumber field is set.
     */
    @Override
    public boolean hasFavoriteNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 favorite_number = 2;</code>
     * @return The favoriteNumber.
     */
    @Override
    public long getFavoriteNumber() {
      return favoriteNumber_;
    }
    /**
     * <code>optional int64 favorite_number = 2;</code>
     * @param value The favoriteNumber to set.
     * @return This builder for chaining.
     */
    public Builder setFavoriteNumber(long value) {
      bitField0_ |= 0x00000002;
      favoriteNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 favorite_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFavoriteNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      favoriteNumber_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInterestsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        interests_ = new com.google.protobuf.LazyStringArrayList(interests_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return A list containing the interests.
     */
    public com.google.protobuf.ProtocolStringList
        getInterestsList() {
      return interests_.getUnmodifiableView();
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return The count of interests.
     */
    public int getInterestsCount() {
      return interests_.size();
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index of the element to return.
     * @return The interests at the given index.
     */
    public String getInterests(int index) {
      return interests_.get(index);
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the interests at the given index.
     */
    public com.google.protobuf.ByteString
        getInterestsBytes(int index) {
      return interests_.getByteString(index);
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param index The index to set the value at.
     * @param value The interests to set.
     * @return This builder for chaining.
     */
    public Builder setInterests(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
      interests_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param value The interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterests(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
      interests_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param values The interests to add.
     * @return This builder for chaining.
     */
    public Builder addAllInterests(
        Iterable<String> values) {
      ensureInterestsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, interests_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterests() {
      interests_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interests = 3;</code>
     * @param value The bytes of the interests to add.
     * @return This builder for chaining.
     */
    public Builder addInterestsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterestsIsMutable();
      interests_.add(value);
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Person)
  }

  // @@protoc_insertion_point(class_scope:Person)
  private static final Person DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Person();
  }

  public static Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @Deprecated public static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @Override
    public Person parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @Override
  public Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

